# Generated by Django 3.1.5 on 2021-01-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderorcart',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
