# Generated by Django 3.1.5 on 2021-01-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210118_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='percentage_off',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
