# Generated by Django 3.1.5 on 2021-01-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productorderorcart_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorderorcart',
            name='total_cost',
        ),
    ]
