# Generated by Django 3.1.5 on 2021-01-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_promocode_percentage_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
