# Generated by Django 3.1.6 on 2021-02-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210131_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='pn', max_length=20),
        ),
    ]
