# Generated by Django 3.1.5 on 2021-01-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('orders', '0005_auto_20210118_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.deal', unique=True),
        ),
    ]
