# Generated by Django 3.1.6 on 2021-02-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210205_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='productorderorcart',
            name='is_ordered',
        ),
    ]
