# Generated by Django 3.1.5 on 2021-01-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('orders', '0009_auto_20210118_1535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('deal', 'cart')},
        ),
    ]
